from pathlib import Path
from datetime import time
import pandas as pd
import numpy as np

# --- FILE PATH SETUP ---
BASE_DIR = Path(__file__).resolve().parent
# Adjust these paths to match your folder structure


# This is the file generated by our Sentiment/Relevance script
NEWS_FILE = BASE_DIR / "final_ai_analysis_report.csv" 
NVDA_FILE = BASE_DIR  / "NVDA_5Y.csv"
QQQ_FILE = BASE_DIR / "QQQ_5Y.csv"
OUT_FILE = BASE_DIR / "nvda_car_sentiment_analysis.csv"

# --- CONSTANTS ---
MARKET_CLOSE = time(16, 0)
CAPM_LOOKBACK = 252  # 1 year of trading days
RISK_FREE_RATE = 0.02 / 252 # Daily risk-free rate (approx)

def load_price_series(path: Path, close_name: str) -> pd.DataFrame:
    df = pd.read_csv(path)
    # Ensure standard column names
    df = df.rename(columns={df.columns[0]: "Date"})
    df["Date"] = pd.to_datetime(df["Date"])
    df[close_name] = pd.to_numeric(df["Close"], errors="coerce")
    return df[["Date", close_name]].dropna().sort_values("Date")

def build_abnormal_returns() -> pd.DataFrame:
    nvda = load_price_series(NVDA_FILE, "Close_NVDA")
    qqq = load_price_series(QQQ_FILE, "Close_QQQ")

    merged = pd.merge(nvda, qqq, on="Date", how="inner").sort_values("Date")
    # Calculate daily returns
    merged["r_nvda"] = merged["Close_NVDA"].pct_change()
    merged["r_qqq"] = merged["Close_QQQ"].pct_change()
    merged = merged.dropna(subset=["r_nvda", "r_qqq"]).reset_index(drop=True)
    return merged

def get_event_date(news_dt: pd.Timestamp) -> pd.Timestamp | None:
    if pd.isna(news_dt):
        return None
    event_date = news_dt.normalize()
    # If news breaks after market close, the event day is the next trading day
    if news_dt.time() >= MARKET_CLOSE:
        event_date = event_date + pd.Timedelta(days=1)
    return event_date

def find_event_index(trading_dates: pd.Series, news_date: pd.Timestamp) -> int | None:
    pos = trading_dates.searchsorted(news_date)
    if pos >= len(trading_dates):
        return None
    return int(pos)

def estimate_capm_beta(returns_df: pd.DataFrame, end_idx: int, lookback: int = CAPM_LOOKBACK) -> float | None:
    start_idx = max(0, end_idx - lookback)
    hist = returns_df.loc[start_idx:end_idx - 1, ["r_nvda", "r_qqq"]].dropna()
    if len(hist) < 30: # Ensure we have enough data for a stable beta
        return None

    r_stock = hist["r_nvda"] - RISK_FREE_RATE
    r_market = hist["r_qqq"] - RISK_FREE_RATE
    
    # Beta = Cov(rs, rm) / Var(rm)
    market_var = np.var(r_market)
    if market_var <= 0:
        return None
    
    covariance = np.cov(r_stock, r_market)[0][1]
    return covariance / market_var

def capm_abnormal_return(r_nvda: float, r_qqq: float, beta: float) -> float:
    # AR = Actual Return - [Rf + Beta * (Rm - Rf)]
    expected = RISK_FREE_RATE + beta * (r_qqq - RISK_FREE_RATE)
    return r_nvda - expected

def compute_car_row(returns_df: pd.DataFrame, t_idx: int) -> tuple:
    # Define window: [-1, +2]
    start = t_idx - 1
    end = t_idx + 2

    if start < 0 or end >= len(returns_df):
        return None, None, None, None

    beta = estimate_capm_beta(returns_df, t_idx)
    if beta is None:
        return None, None, None, None

    window = returns_df.loc[start:end, ["r_nvda", "r_qqq"]].reset_index(drop=True)
    ar_window = window.apply(lambda x: capm_abnormal_return(float(x["r_nvda"]), float(x["r_qqq"]), beta), axis=1)

    # Accumulate returns for CAR
    car_m1 = float(ar_window.iloc[0])           # Day -1
    car_0  = float(ar_window.iloc[0:2].sum())   # Day [-1, 0]
    car_1  = float(ar_window.iloc[0:3].sum())   # Day [-1, 1]
    car_2  = float(ar_window.iloc[0:4].sum())   # Day [-1, 2]
    
    return car_m1, car_0, car_1, car_2

def main() -> None:
    # 1. Load sentiment news (Assuming columns: publish_date, sentiment_score, ai_relevance_score)
    news = pd.read_csv(NEWS_FILE)
    news["publish_date"] = pd.to_datetime(news["publish_date"], errors="coerce")
    
    # Use the sentiment_score column created by the NLTK script
    news["sentiment"] = pd.to_numeric(news["sentiment_score"], errors="coerce")

    # 2. Build Price Returns
    returns_df = build_abnormal_returns()
    trading_dates = returns_df["Date"]

    rows = []
    print("Processing events...")
    
    for _, row in news.iterrows():
        if pd.isna(row["publish_date"]) or pd.isna(row["sentiment"]):
            continue

        event_date = get_event_date(row["publish_date"])
        t_idx = find_event_index(trading_dates, event_date)
        
        if t_idx is None:
            continue

        car_m1, car_0, car_1, car_2 = compute_car_row(returns_df, t_idx)
        
        if car_m1 is not None:
            rows.append({
                "Date": row["publish_date"],
                "CAR_minus_1": car_m1,
                "CAR_0": car_0,
                "CAR_1": car_1,
                "CAR_2": car_2,
                "Sentiment_Score": row["sentiment"],
                "AI_Relevance": row.get("ai_relevance_score", np.nan) # Include relevance if available
            })

    # 3. Output results
    out_df = pd.DataFrame(rows)
    out_df.to_csv(OUT_FILE, index=False)
    print(f"Success! Saved CAR analysis to: {OUT_FILE}")
    print(f"Total events processed: {len(out_df)}")

if __name__ == "__main__":
    main()